#!/bin/sh

unset http_proxy

lb config noauto \
    --binary-images "iso-hybrid" \
    --bootappend-live "locales=de_DE.UTF-8 keyboard-layouts=de persistent noautologin splash vga=788" \
    --debian-installer "live" \
    --debian-installer-distribution "squeeze" \
    --debian-installer-preseedfile "preseed.cfg" \
    --distribution "squeeze" \
    --archive-areas "main contrib non-free" \
    --hostname "efalive" \
    --initramfs "auto" \
    --iso-application "efaLive" \
    --iso-preparer "live-build \$VERSION; http://packages.qa.debian.org/live-build" \
    --iso-publisher "efa project (http://efa.nmichael.de/)" \
    --iso-volume "efaLive \$(date +%Y%m%d-%H:%M)" \
    --language "de" \
    --linux-flavours "486" \
    --linux-packages "linux-image-2.6" \
    --memtest "memtest86+" \
    --mirror-bootstrap "http://localhost:3142/ftp2.de.debian.org/debian/" \
    --mirror-chroot "http://localhost:3142/ftp2.de.debian.org/debian/" \
    --mirror-chroot-security "http://localhost:3142/security.debian.org/" \
    --mirror-chroot-volatile "http://localhost:3142/ftp2.de.debian.org/debian/" \
    --mirror-chroot-backports "http://localhost:3142/backports.debian.org/debian-backports/" \
    --mirror-binary "http://localhost:3142/cdn.debian.net/debian/" \
    --mirror-binary-security "http://localhost:3142/security.debian.org/" \
    --mirror-binary-volatile "http://localhost:3142/cdn.debian.net/debian/" \
    --mirror-binary-backports "http://localhost:3142/backports.debian.org/debian-backports/" \
    --mirror-debian-installer "http://localhost:3142/ftp2.de.debian.org/debian/" \
    --packages "xorg halevt gpm xterm sudo beep zenity zip unzip openbox ssh mailutils anacron python-gtk2 sharutils vim pmount openjdk-6-jre arandr feh sleepd python-gudev less network-manager-gnome network-manager-openvpn network-manager-pptp network-manager-strongswan network-manager-vpnc atmel-firmware firmware-atheros firmware-brcm80211 firmware-intelwimax firmware-iwlwifi firmware-linux-free firmware-linux-nonfree firmware-ralink firmware-realtek libertas-firmware thunar libgnome2-perl" \
    --packages-lists "standard" \
    --security "true" \
    --username "efa" \
    "${@}"

#Nachinstallieren
# firmware-ipw2x00

#Networkmanager Ersatz?
# connman ofono 
