#!/bin/sh

unset http_proxy

#URL_PREFIX="localhost:3142/"
URL_PREFIX=""

lb config noauto \
    --architectures "i386" \
    --linux-flavours "686" \
    --binary-images "iso-hybrid" \
    --bootappend-live "live config hostname=efalive username=efa locales=de_DE.UTF-8 keyboard-layouts=de persistence noautologin splash vga=788" \
    --debian-installer "live" \
    --debian-installer-distribution "bookworm" \
    --distribution "bookworm" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --iso-application "efaLive" \
    --iso-preparer "live-build \$VERSION; http://packages.qa.debian.org/live-build" \
    --iso-publisher "efa project (http://efa.nmichael.de/)" \
    --iso-volume "efaLive 2.8.6 \$(date +%Y%m%d-%H:%M)" \
    --memtest "none" \
    --mirror-bootstrap "http://${URL_PREFIX}deb.debian.org/debian/" \
    --mirror-chroot "http://${URL_PREFIX}deb.debian.org/debian/" \
    --mirror-chroot-security "http://${URL_PREFIX}security.debian.org/" \
    --mirror-binary "http://${URL_PREFIX}cdn.debian.net/debian/" \
    --mirror-binary-security "http://${URL_PREFIX}security.debian.org/" \
    --mirror-debian-installer "http://${URL_PREFIX}deb.debian.org/debian/" \
    --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
    --security "true" \
    --win32-loader "false" \
    --apt-indices false \
    --apt-source-archives false \
    "${@}"

#    --apt-recommends false \
#    --mirror-chroot-backports "http://localhost:3142/backports.debian.org/debian-backports/" \
#    --mirror-binary-backports "http://localhost:3142/backports.debian.org/debian-backports/" \
#    --linux-packages "linux-image" \
#    --bootappend-install "file=/preseed.cfg" \
#    --debian-installer-preseedfile "file:///preseed.cfg" \
