#!/bin/sh
# Change the autogenerated user password to "debianlive"

password="fIvsUlmv70aiA" # as in $(echo "efalive" | mkpasswd -s)
sed -i -e 's/\(_PASSWORD=\)\(.*\)/\1\"'${password}'\"/' /lib/live/config/002-user-setup
update-initramfs -tu -kall

